### ISSUE TITLE
How can i contribute?

### ISSUE THREAD

**Issue by Moshe-Malka** [yassun7010/snowman-py#70]
Hi !
i really like the idea behind this project and would love to help out in promoting this. how can i do that?

**Comment by yassun7010** [comment]
Thanks for your interest ❤️ 

This is a personal project of the idea of a type-safe query builder in Python.

Supporting SELECT is an ambitious goal, but I have no plans to start working on it at the moment.

However, I would be very happy if you could enhance this idea with a perspective other than mine.

If you have any features you would like to add to this project, please let me know by Issue or PR.

**Comment by Moshe-Malka** [comment]
there is no proper query builder for Snowflake, and i think you got a good start in this project.

**Comment by yassun7010** [comment]
[snowflake-sqlalchemy](https://pypi.org/project/snowflake-sqlalchemy/) recently added support for sqlalchemy v2;
and sqlalchemy v2 provides a more SQL-like writing style.
If you are still not satisfied, we may want to promote this project.

I am cautious about implementing a SELECT clause because I believe it is a complex feature and that current Python is not powerful enough to create a type-safe (i.e. truly robust) query builder.

Type Script has a more advanced ORM and [drizzle](https://orm.drizzle.team/docs/select) is closer to my idea.

Note that I am open to Issues and PR.

**Comment by yassun7010** [comment]
[v0.0.31](https://github.com/yassun7010/snowman-py/tree/v0.0.31) 

v0.0.31 was released and implements [an experimental select](https://yassun7010.github.io/snowman-py/guide/query_builder/#select-query).
JOIN clause is not yet available, but simple SELECT can be used type-safely.

If snowflake-sqlalchemy v2 is not enough for you, we can expand on this idea and proceed to create a type-safe query builder ; )
